### ISSUE TITLE
Tank can get stuck in the game

### ISSUE THREAD

**Issue by kylerippey** [SeaRbSg/elixir#16] opened 2015-07-29 02:16 UTC
Apparently, I put my macbook to sleep with a tab still open and a tank still in the game on production. When I woke the machine I closed all the tabs, but apparently my tank is still active in the game. I haven't investigated the cause yet.

**Comment by dazuma** [comment] 2015-07-29 02:28
Yeah, confirmed, your Player object is still there. The code is supposed to detect if the websocket dies and remove the player, but it's possible either the websocket didn't close down cleanly or the code is wrong.

**Comment by dazuma** [comment] 2015-08-02 16:38
Looks like a client can indeed go away without properly closing the websocket. I think the approach I'll take to fix this is to implement a heartbeat. If the client isn't actively requesting animation frames (e.g. because its tab is backgrounded) then it will at least send a heartbeat message every minute or so. Then the server can kill a player if it hasn't received any messages for some length of time.

**Comment by dazuma** [comment] 2015-08-06 14:25
Based on a quick discussion with Chris McCord, I ended up solving this by trapping exits on the channel process in the server. This causes unexpected process exits (which is what will eventually happen when a websocket gets into this state) to trigger the terminate callback.

**Closed as completed by dazuma** 2015-08-06 14:25 UTC
Labels: bug
